"""Who ruled on an error candidate, and when.

`dismiss_error` set status and committed. Nothing recorded who dismissed it or at what time, so a dismissal
was an unattributable state change on a row that had been generated by a machine. Confirmations at least
leave a Review row; dismissals left nothing at all.

That matters more than ordinary audit hygiene here, because dismissals are the calibration data. The
detectors have produced 298,529 candidates and hold exactly one confirmed verdict, so nothing about their
precision can be computed. Once verdicts exist in volume, confirmed over confirmed-plus-dismissed is the
per-detector precision, which is the number that decides whether a detector deserves a place in the queue at
all. A dismissal with no timestamp cannot be attributed to a detector version or a period, so the number it
feeds would be untraceable the moment anything changed.

`decision_note` exists because bulk verdicts need a reason that survives. Dismissing 400 near-duplicate
candidates in one action is a judgement about the detector, not about 400 objects, and the reason for it is
the most useful thing in the row.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0084_error_candidate_decision"
down_revision = "0083_usage_record"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("error_candidate", sa.Column(
        "decided_by", postgresql.UUID(as_uuid=True),
        sa.ForeignKey("app_user.user_id", ondelete="SET NULL"), nullable=True))
    op.add_column("error_candidate", sa.Column(
        "decided_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("error_candidate", sa.Column("decision_note", sa.Text(), nullable=True))
    # Per-detector precision is grouped by kind and filtered to decided rows, which is the query that turns
    # this table into calibration data rather than a backlog.
    op.create_index("ix_error_candidate_kind_status", "error_candidate", ["kind", "status"])


def downgrade() -> None:
    op.drop_index("ix_error_candidate_kind_status", table_name="error_candidate")
    op.drop_column("error_candidate", "decision_note")
    op.drop_column("error_candidate", "decided_at")
    op.drop_column("error_candidate", "decided_by")
